name: coredumpedapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animate_gradient: ^0.0.2+1
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  flutter_bloc: ^8.1.3
  google_sign_in: ^6.1.5
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/































