name: Flutter CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - main
jobs:
  flutter_test:
    name: Run Flutter Test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: actions/setup-java@v3.13.0
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: stable
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
